version: '3.6'

services:
  chatgpt:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env.local
    depends_on:
      - db

  db:
    image: postgres
    hostname: db
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
      POSTGRES_DB: chatui
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    expose:
      - 5432

  dex:
    image: ghcr.io/dexidp/dex:latest-alpine
    user: root
    volumes:
      - ./dex/config.yaml:/etc/dex/config.docker.yaml
    ports:
      - 5556:5556
    expose:
      - 5556

volumes:
  pgdata:
